name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when you push to the 'main' branch

permissions:
  contents: write  # Allows GitHub to write to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build && npm run export

      - name: Setup GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: out  # Deploy the 'out' folder (Next.js export output)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
